g3w-admin/OWS/urls.py
"""
Add your API routes here.
"""
# API ROOT: /:lang/admin/

__author__    = 'lorenzetti@gis3w.it'
__copyright__ = 'Copyright 2015 - 2023, Gis3w'
__license__   = "MPL 2.0"

from django.urls import re_path

from .views import *


app_name = 'OWS'

urlpatterns = [

    #############################################################
    # Main OWS client
    #############################################################
    re_path(
        r'^ows/(?P<map_name_alias>[-_\w\d]+)/&?$',
        ows_alias_view,
        name='ows-alias'
    ),

    re_path(
        r'^ows/(?P<group_slug>[-_\w\d]+)/(?P<project_type>[-_\w\d]+)/(?P<project_id>[-_\w\d]+)/&?$',
        OWSView.as_view(),
        name='ows'
    ),

    re_path(
        r'^ows/(?P<group_slug>[-_\w\d]+)/(?P<project_type>[-_\w\d]+)/(?P<project_id>[-_\w\d]+)/wfs3&?',
        OWSView.as_view(),
        name='ows-wfs3'
    ),

]

g3w-admin/client/urls.py
"""
Add your API routes here.
"""
# API ROOT: /:lang/admin/

__author__    = 'lorenzetti@gis3w.it'
__copyright__ = 'Copyright 2015 - 2023, Gis3w'
__license__   = "MPL 2.0"

from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from .views import *

from .branch_manager import ClientBranchManagerView


USER_MEDIA_PREFIX = 'me'

urlpatterns = [

    #############################################################
    # G3W-CLIENT bootstrap
    #############################################################
    re_path(
        r'^map/(?P<map_name_alias>[-_\w\d]+)/$',
        client_map_alias_view,
        name='group-project-map-alias'
    ),

    re_path(
        r'^map/(?P<group_slug>[-_\w\d]+)/(?P<project_type>[-_\w\d]+)/(?P<project_id>[0-9]+)/$',
        ClientView.as_view(),
        name='group-project-map'
    ),

    re_path(
        r'^map/(?P<group_slug>[-_\w\d]+)/(?P<project_type>[-_\w\d]+)/(?P<project_slug>[-_\w\d]+)/$',
        ClientView.as_view(),
        name='group-project-slug-map'
    ),

    #############################################################
    # Media reading upload
    #############################################################
    re_path(
        r'^{}/(?P<project_type>[-_\w\d]+)/(?P<layer_id>[0-9]+)/(?P<file_name>[\(\)"\'-_. \w\d]+)'.format(USER_MEDIA_PREFIX),
        user_media_view,
        name='user-media'
    ),

    path(
        'credits/',
        credits,
        name='client-credits'
    ),

    path(
        'admin/client-branch/',
        login_required(ClientBranchManagerView.as_view()),
          name='client-branch-manager'
    ),
]

g3w-admin/core/urls.py
"""
Add your API routes here.
"""
# API ROOT: /:lang/admin/

__author__    = 'lorenzetti@gis3w.it'
__copyright__ = 'Copyright 2015 - 2023, Gis3w'
__license__   = "MPL 2.0"

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.static import serve

from client.api.views import *
from .views import *


def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


urlpatterns = [

    #############################################################
    # General
    #############################################################
    path(
        '',
        login_required(DashboardView.as_view()),
        name='home'
    ),

    path(
        'generalsuitedata/',
        login_required(GeneralSuiteDataUpdateView.as_view()),
        name='generaldata-update'
    ),

    path(
        'search/',
        login_required(SearchAdminView.as_view()),
        name='search-admin'
    ),

    #############################################################
    # Macro Groups
    #############################################################
    path(
        'macrogroups/',
        login_required(MacroGroupListView.as_view()),
        name='macrogroup-list'
    ),

    path(
        'macrogroups/add/',
        login_required(MacroGroupCreateView.as_view()),
        name='macrogroup-add'
    ),

    path(
        'macrogroups/update/<slug:slug>/',
        login_required(MacroGroupUpdateView.as_view()),
        name='macrogroup-update'
    ),

    path(
        'macrogroups/delete/<slug:slug>/',
        login_required(MacroGroupDeleteView.as_view()),
        name='macrogroup-delete'
    ),

    path(
        'macrogroups/<slug:slug>/',
        login_required(MacroGroupDetailView.as_view()),
        name='macrogroup-detail'
    ),

    #############################################################
    # Groups
    #############################################################
    path(
        'groups/',
        login_required(GroupListView.as_view()),
        name='group-list'
    ),

    path(
        'groups/deactivated/',
        login_required(GroupDeactiveListView.as_view()),
        name='group-deactive-list'
    ),

    path(
        'groups/add/',
        login_required(GroupCreateView.as_view()),
        name='group-add'
    ),

    path(
        'groups/update/<slug:slug>/',
        login_required(GroupUpdateView.as_view()),
        name='group-update'
    ),

    path(
        'groups/deactive/<slug:slug>/',
        login_required(GroupDeActiveView.as_view()),
        name='group-deactive'
    ),

    path(
        'groups/active/<slug:slug>/',
        login_required(GroupActiveView.as_view()),
        name='group-active'
    ),

    path(
        'groups/delete/<slug:slug>/',
        login_required(GroupDeleteView.as_view()),
        name='group-delete'
    ),

    path(
        'groups/<slug:slug>/',
        login_required(GroupDetailView.as_view()),
        name='group-detail'
    ),

    path(
        'jx/groups/<slug:slug>/setpanoramic/<project_type>/<int:project_id>/',
        login_required(GroupSetProjectPanoramicView.as_view()),
        name='group-set-project-panoramic'
    ),
    
    path(
        'jx/groups/<slug:slug>/setpanoramic/<project_type>/<project_id>/',
        login_required(GroupSetProjectPanoramicView.as_view()),
        name='group-set-project-panoramic'
    ),

    #############################################################
    # Projects
    #############################################################
    path(
        'groups/<slug:group_slug>/projects/',
        login_required(ProjectListView.as_view()),
        name='project-list'
    ),
    #############################################################
    # System
    #############################################################
    path(
        'systeminfo/',
        login_required(SystemInfoView.as_view()),
        name='systeminfo'
    ),

]

g3w-admin/core/models.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.db import models
from django.apps import apps
from guardian.shortcuts import get_objects_for_user
from guardian.compat import get_user_model
from ordered_model.models import OrderedModel
from model_utils.models import TimeStampedModel
from sitetree.models import TreeItemBase, TreeBase
from django.contrib.auth.models import User, Group as AuthGroup
from usersmanage.utils import setPermissionUserObject, getUserGroups, get_users_for_object, get_groups_for_object
from usersmanage.configs import *
from .utils.structure import getProjectsByGroup
from .fields import AutoSlugField
try:
    from osgeo import osr
except:
    pass

import string
import random
import logging

class G3W2Tree(TreeBase):
    module = models.CharField(_('Qdjango2 module'), max_length=50, null=True, blank=True)


class G3W2TreeItem(TreeItemBase):
    type_header = models.BooleanField(_('Type header'), default=False, blank=True)
    icon_css_class = models.CharField(_('Icon CSS class'), max_length=50,null=True, blank=True)


class G3WSpatialRefSys(models.Model):
    """
    Clone of Postgis spatial_ref_sys for no geo database
    """
    srid = models.IntegerField(_('SRID'), primary_key=True)
    auth_name = models.CharField(_('SRS name'), max_length=256)
    auth_srid = models.IntegerField(_('SRS ID'))
    srtext = models.CharField(_('WKT SRS'), max_length=2048)
    proj4text = models.CharField(_('PROJ coordinate definition'), max_length=2048)

    def __str__(self):
        '''
        try:
            sref = osr.SpatialReference()
            sref.ImportFromWkt(self.srtext)
            return "{} - [{}] - {}".format(str(self.srid), sref.GetLinearUnitsName(), sref.GetAttrValue())
        except Exception as e:
        '''
        return "{} {}".format(self.auth_name, str(self.srid))


class BaseLayer(OrderedModel):
    """
    Model to store Base layers
    """
    name = models.CharField(_('Name'), max_length=255)
    title = models.CharField(_('Title'), max_length=255)
    icon = models.ImageField(_('Icon'), null=True, blank=True)
    description = models.TextField(_('Description'), null=True, blank=True)
    property = models.TextField(_('Property'))

    def __str__(self):
        return "{} ({})".format(self.title, self.name)

    class Meta(OrderedModel.Meta):
        verbose_name = _('Base Layer')
        verbose_name_plural = _('Base Layers')


class MapControl(OrderedModel):
    """
    Model for Map Controls: zoom, query, etc..
    """
    name = models.CharField(_('Name'), max_length=255)
    description = models.TextField(_('Description'), null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta(OrderedModel.Meta):
        verbose_name = _('Map control')
        verbose_name_plural = _('Map controls')


class MacroGroup(TimeStampedModel, OrderedModel):
    """
    Model for Macro groups, no ACL
    """

    name = models.CharField(_('Identification name'), max_length=255, null=True,
                            help_text=_('Internal identification Macrogroup name'))
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), blank=True)
    logo_img = models.FileField(_('Logo image'), upload_to='macrogroup/logo_img')
    logo_link = models.URLField(_('Logo link'), blank=True, null=True,
                                       help_text=_('Enter link with http:// or https//'))
    use_title_client = models.BooleanField(_('Use title for client'), default=False)
    use_logo_client = models.BooleanField(_('Use logo image for client'), default=False)

    slug = AutoSlugField(
        _('Slug'), unique=True, populate_from=['name'])

    def __str__(self):
        return self.title

    def _permissions_to_editors(self, users_id, mode='add'):

        for user_id in users_id:
            setPermissionUserObject(User.objects.get(pk=user_id), self, permissions='view_macrogroup', mode=mode)

    def add_permissions_to_editors(self, users_id):
        """
        Give guardian permissions to Editors
        """
        self._permissions_to_editors(users_id, 'add')

    def remove_permissions_to_editors(self, users_id):
        """
        Remove guardian permissions to Editors
        """
        self._permissions_to_editors(users_id, 'remove')

    class Meta():
        verbose_name = _('MACRO Group')
        verbose_name_plural = _('MACRO Groups')
        ordering = ("order",)


class Group(TimeStampedModel, OrderedModel):
    """A group of projects."""
    # General info
    name = models.CharField(_('Name'), max_length=255, unique=True)
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), blank=True)
    slug = AutoSlugField(
        _('Slug'), populate_from=['name'], unique=True
        )
    is_active = models.BooleanField(_('Is active'), default=1)

    # Company logo
    header_logo_img = models.FileField(_('Logo image'), upload_to='logo_img',
                                       default=f'logo_img/{settings.CLIENT_G3WSUITE_LOGO}')
    header_logo_link = models.URLField(_('Logo link'), blank=True, null=True,
                                       help_text=_('Enter link with http:// or https//'))

    # Group SRID (a.k.a. EPSG)
    srid = models.ForeignKey(G3WSpatialRefSys, db_column='srid', on_delete=models.DO_NOTHING, verbose_name=_('SRID'))

    # baselayers
    baselayers = models.ManyToManyField(BaseLayer, blank=True, verbose_name=_('Base layers'))

    # mapcontrols
    mapcontrols = models.ManyToManyField(MapControl, verbose_name=_('Map controls'))

    # background color map default
    background_color = models.CharField(_('Background color'), max_length=7, default='#ffffff', blank=True)

    # Company TOS
    header_terms_of_use_text = models.TextField(
        _('Terms of use text'), blank=True
        )
    header_terms_of_use_link = models.URLField(
        _('Terms of use link'), blank=True
        )

    macrogroups = models.ManyToManyField(MacroGroup, blank=True, verbose_name=_('MACRO groups'))

    use_logo_client = models.BooleanField(_('Use logo image for client'), default=False,
                                          help_text=_('As for MacroGroup options is possible to use current logo group '
                                                      'as client logo, if MacroGroup option is active this options takes '
                                                      'precendence'))

    class Meta():
        verbose_name = _('Group')
        verbose_name_plural = _('Groups')
        permissions = (
            ('add_project_to_group', 'Can add project to the group'),
        )
        ordering = ("order",)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('group-detail', kwargs={'slug': self.slug})

    def get_panoramic_project(self):
        try:
            group_pano_project = GroupProjectPanoramic.objects.get(group=self)
            Project = apps.get_app_config(group_pano_project.project_type).get_model('project')
            return Project.objects.get(pk=group_pano_project.project_id)
        except:
            return None

    def getProjects(self):
        """
        Get every type projects for group
        """
        groupProjects = []
        for g3wProjectApp in settings.G3WADMIN_PROJECT_APPS:
            Project = apps.get_app_config(g3wProjectApp).get_model('project')
            projects = Project.objects.filter(group=self).order_by('title')
            groupProjects += [(g3wProjectApp, project) for project in projects]
        return groupProjects

    def getProjectsNumber(self, user=None, is_active=None):
        """
        Count total number of serveral type project
        :return: integer
        """
        groupProjects = 0
        for g3wProjectApp in settings.G3WADMIN_PROJECT_APPS:
            Project = apps.get_app_config(g3wProjectApp).get_model('project')
            if user:
                qs = get_objects_for_user(user, '{}.view_project'.format(g3wProjectApp), Project) \
                    .filter(group=self)
            else:
                qs = Project.objects.filter(group=self)

            if is_active and is_active in (0, 1):
                qs = qs.filter(is_active=is_active)

            groupProjects += len(qs)

        return groupProjects

    def addPermissionsToEditor(self, user):
        """
        Give guardian permissions to Editor every level
        """

        permissions = ['view_group', 'add_project_to_group'] # valid for editor2
        user_groups = getUserGroups(user)
        if G3W_EDITOR1 in user_groups:
            permissions += [
                'add_project_to_group',
                'change_group',
                'delete_group'
            ]

        setPermissionUserObject(user, self, permissions=permissions)

        # adding permissions to projects
        appProjects = getProjectsByGroup(self)
        for app, projects in list(appProjects.items()):
            for project in projects:
                project.addPermissionsToEditor(user)

    def removePermissionsToEditor(self, user):
        """
        Remove guardian permissions to Editor
        """

        setPermissionUserObject(user, self, permissions=[
            'change_group',
            'delete_group',
            'view_group',
            'add_project_to_group'
        ], mode='remove')

        # adding permissions to projects
        appProjects = getProjectsByGroup(self)
        for app, projects in list(appProjects.items()):
            for project in projects:
                project.removePermissionsToEditor(user)

    def addPermissionsToViewers(self, users_id, **kwargs):
        """
        Give guardian permissions to Viewers
        """
        appProjects = getProjectsByGroup(self)

        for user_id in users_id:

g3w-admin/core/utils/models.py
from model_utils import Choices


class G3WChoices(Choices):
    """
    Custom G3W model_utils widget.
    """
    def __setitem__(self, key, value):
        self._store((key, key, value), self._triples, self._doubles)

g3w-admin/core/templates/core/403_MGC.html
{% extends "base.html" %}
{% load i18n %}

{%  block page_header %}
<h1>
403
<small>{% trans "error page" %}</small>
</h1>
{% endblock %}

{% block main_content %}
<div class="error-page">
<h2 class="headline text-yellow"> 403</h2>
<div class="error-content">
    <h3><i class="fa fa-warning text-yellow"></i> {% trans 'Access denied' %}!!</h3>
    <h4>
    {% trans "You can't add new Group" %}.
    </h4>
</div><!-- /.error-content -->
</div><!-- /.error-page -->
{% endblock %}

g3w-admin/core/templates/core/403_MPC.html
{% extends "base.html" %}
{% load i18n %}

{%  block page_header %}
<h1>
403
<small>{% trans "error page" %}</small>
</h1>
{% endblock %}

{% block main_content %}
<div class="error-page">
<h2 class="headline text-yellow"> 403</h2>
<div class="error-content">
    <h3><i class="fa fa-warning text-yellow"></i> {% trans 'Access denied' %}!!</h3>
    <h4>
    {% trans "You can't add new Project" %}.
    </h4>
</div><!-- /.error-content -->
</div><!-- /.error-page -->
{% endblock %}

g3w-admin/core/templates/core/generalsuitedata_form.html
{% extends "base.html" %}
{% load static %}
{% load g3wadmin_tags %}
{% load crispy_forms_tags %}
{% load guardian_tags %}
{% load i18n %}


{% block page_header %}
<h1>
    {% trans 'General suite data' %}
    <small>{{ form.instance.name }}</small>
</h1>
{% endblock %}

{% block main_content %}


<form method="post" id="generalsuitedata-form" data-widget-type="ajaxUpload"   enctype="multipart/form-data">
    {% if form.errors %}
        <div class="row">
            <div class="col-md-12">
            <div class="alert alert-danger alert-dismissable">
                <h4><i class="icon fa fa-ban"></i> {% trans 'Alert' %}!</h4>
                    {% trans 'Some errors on form. Check it and send again.' %}
              </div>
            </div>
        </div>
    {% endif %}
    {% crispy form %}
    {% g3wadmin_add_button_form%}
</form>

{% endblock %}

g3w-admin/core/templates/core/group_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load guardian_tags %}
{% load auth_extras %}
{% load i18n %}
{% load g3wadmin_tags %}

{% block page_header %}
    <h1>{% trans 'Cartographic groups' %}</h1>
{% endblock %}

{% block custom_js_links_page %}
{% if user.is_superuser %}
<script>
    $("#groups_list").sortable({
        placeholder: "col-md-3 col-sm-6 sort-highlight-group",
        handle: ".handle",
        update: function(e, ui){
            new_order = $(e.target).sortable("toArray");

            // get current id of group moved
            var gid = ui.item.attr('id').substring(6)
            var url = _.template("/jx/groups/<%= gid %>/setorder/")({gid: gid});
            var data = {
                new_order: new_order
            }
            ga.utils.addCsfrtokenData(data);

            $.post(url, data, function(res){
                console.log(res);
            });

        },
    });
    $("#groups_list").disableSelection();
    $('.handle').hover(function() {
        $(this).css('cursor','move');
    });
</script>
{% endif %}
{% endblock %}

{% block main_content %}

<div id="group_list_fitler_bar" class="row">
<section class="col-lg-5">
    <div class="box box-solid {% if collapsed_filter_form %}collapsed-box{% endif %}">
            <div class="box-header ui-sortable-handle" style="cursor: move;">
              <i class="fa fa-filter"></i>
              <h3 class="box-title">{% trans 'Filter by' %}</h3>
              <div class="box-tools pull-right">
                <button type="button" class="btn btn-sm" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body border-radius-none">
                <form method="get" id="group-filter">
                {% crispy filter_form  %}
                    <button class="btn btn-block btn-default">{% trans 'Filter' %}</button>
                </form>
            </div>
          </div>
</section>
</div>
<div id="groups_list" class="row">
{% for object in object_list %}
    {% get_obj_perms user for object as "userObj_perms" %}
    <div class="col-md-3 col-sm-6" id="group_{{ object.pk }}">
     <div class="box box-widget widget-user" id="group_{{ object.slug }}">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-aqua-active col-sm-12" style="background: url('{{ MEDIA_URL }}{{ object.header_logo_img }}') no-repeat center center;">
                <div class="row">
                    <div class="col-sm-12 widget-group-title handle">
                        <h3 class="widget-user-username">{{ object.name }}</h3>
                        <h5 class="widget-user-desc">{{ object.title }} <small>({{ object.srid }})</small></h5>
                    </div>
                </div>
                </div>
                <div class="box-footer">
                  <div class="row">
                   <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                        {% if "change_group" in userObj_perms %}
                        <div class="icon" data-toggle="tooltip" data-placement="top" title="{% trans 'Add new project' %}" >
                        {% if SETTINGS.G3WADMIN_PROJECT_APPS|length == 1 %}
                            <a href="{% url 'qdjango-project-add' object.slug %}" ><i class="ion ion-plus-circled"></i></a>
                        {% else %}
                            {% include 'core/include/add_project.html' %}
                        {% endif %}
                        </div>
                        {% endif %}
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-4 col-xs-4">
                      <div class="description-block projects-group">
                        <h5 class="description-header"  data-toggle="tooltip" data-placement="top" title="{% trans 'Group projects' %}" ><a href="{% url 'project-list' object.slug %}">{% g3wadmin_get_projects_number object user 1 %} {% trans 'Projects' %}</a></h5>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                         <div class="icon">
                         {% if "view_group" in userObj_perms %}
                          <a href="#" data-toggle="tooltip" data-placement="top" title="{% trans 'Show detail' %}" data-widget-type="detailItem" data-detail-url="{% url 'group-detail' object.slug %}"><i class="ion ion-eye"></i></a>
                         {% endif %}
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                        <div class="icon">
                        {% if "change_group" in userObj_perms %}
                          <a href="{% url 'group-update' object.slug %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}" ><i class="ion ion-edit"></i></a>
                        {% endif %}
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                        <div class="icon">
                        {% if "delete_group" in userObj_perms %}
                          <a href="#" 
                          data-toggle="tooltip" 
                          data-placement="top" 
                          title="{% trans 'Delete/Deactivate' %}"  
                          data-widget-type="activeDeactiveItem" 
                          data-active-deactive-action="deactivate" 
                          data-active-deactive-url="{% url 'group-deactive' object.slug %}"
                          data-active-deactive-delete-url="{% url 'group-delete' object.slug %}"
                          data-item-selector="#group_{{ object.slug }}">
                          <i class="ion ion-trash-b"></i></a>
                        {% endif %}
                            <div class="hidden pre-active-deactive-message">
                                <div><p>{% blocktrans %}<strong>Warning</strong>: deleting the group (move to bucket) will delete the projects it contains (move to the bucket)!{% endblocktrans %}</p></div>
                            </div>
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                  </div><!-- /.row -->
                </div>
          </div><!-- /.widget-user -->
    </div>
{% endfor %}
</div>
{% if perms.core.add_group %}
<div class="row">
{% with 'group-add' as object_add_url_name %}
    {% include 'core/include/widget_add_box.html' %}
{% endwith %}
</div>
{% endif %}

{% endblock %}

g3w-admin/core/templates/core/macrogroup_form.html
{% extends "base.html" %}
{% load static %}
{% load g3wadmin_tags %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_header %}
<h1>
    {% trans 'Macro Group' %}

    {% if form.instance.name %}
    <small>{{ form.instance.name }}</small>
    {% endif %}
</h1>
{% endblock %}



{% block main_content %}

{% if object %}
    <div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{% trans 'Current groups' %}</h3>
                {% comment %}
                <h3 class="box-title">
                    {% include 'core/include/add_project.html' %}
                </h3>
                {% endcomment %}
            </div>
            <div class="box-body">
            {% comment %}
                <h4>{% trans 'Current groups' %}</h4>
            {% endcomment %}
                {% for group in object.group_set.all %}
                <a href="{% url 'group-update' group.slug %}">{{ group }}</a> {% if not forloop.last %} | {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}

<form method="post" id="macrogroup-form" data-widget-type="ajaxUpload"  enctype="multipart/form-data">
    {% if form.errors %}
        <div class="row">
            <div class="col-md-12">
            <div class="alert alert-danger alert-dismissable">
                <h4><i class="icon fa fa-ban"></i> {% trans 'Alert' %}!</h4>
                    {% trans 'Some errors on form. Check it and send again.' %}
              </div>
            </div>
        </div>
    {% endif %}
    {% crispy form %}
    {% g3wadmin_add_button_form%}
</form>

{% endblock %}

g3w-admin/core/templates/core/macrogroup_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load guardian_tags %}
{% load auth_extras %}
{% load i18n %}
{% load g3wadmin_tags %}

{% block page_header %}
    <h1>{% trans 'Cartographic macro groups' %}</h1>
{% endblock %}


{% block custom_js_links_page %}
{% if user.is_superuser %}
<script>
    $("#macrogroups_list").sortable({
        placeholder: "col-md-3 col-sm-6 sort-highlight-group",
        handle: ".handle",
        update: function(e, ui){
            new_order = $(e.target).sortable("toArray");

            // get current id of group moved
            var gid = ui.item.attr('id').substring(11)
            var url = _.template("/jx/macrogroups/<%= gid %>/setorder/")({gid: gid});
            var data = {
                new_order: new_order
            }
            ga.utils.addCsfrtokenData(data);

            $.post(url, data, function(res){
                console.log(res);
            });

        },
    });
    $("#groups_list").disableSelection();
    $('.handle').hover(function() {
        $(this).css('cursor','move');
    });
</script>
{% endif %}
{% endblock %}

{% block main_content %}


<div id="macrogroups_list" class="row">
{% for object in object_list %}
    {% get_obj_perms user for object as "userObj_perms" %}
    <div class="col-md-3 col-sm-6" id="macrogroup_{{ object.pk }}">
     <div class="box box-widget widget-user" id="macrogroup_{{ object.slug }}">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-aqua-active col-sm-12" style="background: url('{{ MEDIA_URL }}{{ object.logo_img }}') center center;">
                <div class="row">
                    <div class="col-sm-12 widget-group-title handle">
                        <h3 class="widget-user-username">{{ object.title }}</h3>
                    </div>
                </div>
                </div>
                <div class="box-footer">
                  <div class="row">
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                         <div class="icon">
                          <a href="#" data-toggle="tooltip" data-placement="top" title="{% trans 'Show detail' %}" data-widget-type="detailItem" data-detail-url="{% url 'macrogroup-detail' object.slug %}"><i class="ion ion-eye"></i></a>
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                        <div class="icon">
                        {% if "change_macrogroup" in userObj_perms %}
                          <a href="{% url 'macrogroup-update' object.slug %}" data-toggle="tooltip" data-placement="top" title="{% trans 'Edit' %}" ><i class="ion ion-edit"></i></a>
                        {% endif %}
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                    <div class="col-sm-2 col-xs-2">
                      <div class="description-block">
                        <div class="icon">
                        {% if "delete_macrogroup" in userObj_perms %}
                          <a href="#" data-toggle="tooltip" data-placement="top" title="{% trans 'Delete' %}"  data-widget-type="deleteItem" data-delete-url="{% url 'macrogroup-delete' object.slug %}" data-item-selector="#macrogroup_{{ object.slug }}"><i class="ion ion-trash-b"></i></a>
                        {% endif %}
                        </div>
                      </div><!-- /.description-block -->
                    </div><!-- /.col -->
                  </div><!-- /.row -->
                </div>
          </div><!-- /.widget-user -->
    </div>
{% endfor %}
</div>
{% if perms.core.add_group %}
<div class="row">
{% with 'macrogroup-add' as object_add_url_name %}
    {% include 'core/include/widget_add_box.html' %}
{% endwith %}
</div>
{% endif %}


{% endblock %}